/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Globe = props => {
    const { nodes, materials } = useGLTF('/models/globe.glb')
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Earth.geometry} material={materials.EarthHologram} rotation={[0, -0.553, -0.161]} />
        </group>
    )
}

useGLTF.preload('/models/globe.glb')

export default Globe
